### ISSUE TITLE
ImportError: No module named webApplication

### ISSUE THREAD

**Issue by zhujinhe** [guillaume-philippon/python-itop-api#22]
Thanks for your great work on this useful api. 
I got an error:

```
user@machine> itop-cli
Traceback (most recent call last):
  File "./itop-cli", line 11, in <module>
    from itopapi import ItopapiController, ItopapiConfig, UnsupportedImportFormat
  File "/root/python-itop-api-master/itopapi/__init__.py", line 10, in <module>
    from itopapi.model import ItopapiRack, ItopapiServer
  File "/root/python-itop-api-master/itopapi/model/__init__.py", line 19, in <module>
    from itopapi.model.webApplication import ItopapiWebApplication
ImportError: No module named webApplication
```

May be we should 
rename the ./itopapi/model/webapplication.py to itopapi/model/webApplication.py 
or modify `from itopapi.model.webApplication import ItopapiWebApplication` to `from itopapi.model.webapplication import ItopapiWebApplication`.

**Comment by JulienNauroy** [comment]
Hi,

If you're still interested in the project, you can check if the problem persists with this branch : https://github.com/JulienNauroy/python-itop-api
It should be merged back into Guillaume's repository pretty soon.
